# Generated by Django 4.1.3 on 2023-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aptitude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_questions", models.PositiveIntegerField()),
                ("marks", models.PositiveIntegerField()),
            ],
        ),
    ]
