# Generated by Django 4.1.3 on 2023-01-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_aptitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.PositiveIntegerField()),
                ("question", models.CharField(max_length=600)),
                ("option1", models.CharField(max_length=200)),
                ("option2", models.CharField(max_length=200)),
                ("option3", models.CharField(max_length=200)),
                ("option4", models.CharField(max_length=200)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("Option1", "Option1"),
                            ("Option2", "Option2"),
                            ("Option3", "Option3"),
                            ("Option4", "Option4"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "aptitude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.aptitude"
                    ),
                ),
            ],
        ),
    ]
